Repository www-author/springboot-lol-community, pull requests merged in 2024-04, with the labels that each got.

#22 feat: 로그인 기능 구현
  .gitignore
  README.md
  build.gradle
  src/main/java/com/lol/community/board/controller/BoardApiController.java
  src/main/java/com/lol/community/board/controller/BoardController.java
  src/main/java/com/lol/community/board/domain/Board.java
  src/main/java/com/lol/community/board/domain/BoardType.java
  src/main/java/com/lol/community/board/dto/request/BoardRequest.java
  src/main/java/com/lol/community/board/dto/response/BoardBaseResponse.java
  src/main/java/com/lol/community/board/dto/response/BoardResponse.java
  src/main/java/com/lol/community/board/repository/BoardRepository.java
  src/main/java/com/lol/community/board/service/BoardService.java
  src/main/java/com/lol/community/board/service/BoardServiceImpl.java
  src/main/java/com/lol/community/category/domain/Category.java
  src/main/java/com/lol/community/category/dto/CategoryResponse.java
  src/main/java/com/lol/community/category/repository/CategoryRepository.java
  src/main/java/com/lol/community/category/service/CategoryService.java
  src/main/java/com/lol/community/comment/Comment.java
  src/main/java/com/lol/community/global/BaseEntity.java
  src/main/java/com/lol/community/global/config/JpaAuditingConfig.java
  src/main/java/com/lol/community/global/config/SwaggerConfig.java
  src/main/java/com/lol/community/global/config/WebConfig.java
  src/main/java/com/lol/community/global/config/WebSecurityConfig.java
  src/main/java/com/lol/community/user/controller/LoginController.java
  src/main/java/com/lol/community/user/controller/UserController.java
  src/main/java/com/lol/community/user/domain/GradeCode.java
  src/main/java/com/lol/community/user/domain/User.java
  src/main/java/com/lol/community/user/form/LoginForm.java
  src/main/java/com/lol/community/user/form/UserEditForm.java
  src/main/java/com/lol/community/user/form/UserSaveForm.java
  src/main/java/com/lol/community/user/login/Login.java
  src/main/java/com/lol/community/user/login/LoginMemberArgumentResolver.java
  src/main/java/com/lol/community/user/login/SessionConst.java
  src/main/java/com/lol/community/user/login/SessionValue.java
  src/main/java/com/lol/community/user/repository/UserRepository.java
  src/main/java/com/lol/community/user/repository/UserRepositoryImpl.java
  src/main/java/com/lol/community/user/service/LoginService.java
  src/main/java/com/lol/community/user/service/UserService.java
  src/main/java/com/lol/community/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/img/footer_img.png
  src/main/resources/static/img/lock_img.png
  src/main/resources/static/img/logo.png
  src/main/resources/static/img/logo_top.png
  src/main/resources/static/img/user.png
  src/main/resources/static/img/user_img.png
  src/main/resources/static/index.html
  src/main/resources/static/js/article.js
  src/main/resources/templates/login/loginForm.html
  src/main/resources/templates/newArticle.html
  src/main/resources/templates/report.html
  src/main/resources/templates/users/addUserForm.html
  src/main/resources/templates/users/editUserForm.html
  src/test/java/com/lol/community/board/controller/BoardApiControllerTest.java
Labels: BE🍴, 개발💻🖱️, feat🚀

#28 feat : 메인 화면 Top N 조회 및 게시글
  src/main/java/com/lol/community/board/controller/BoardApiController.java
  src/main/java/com/lol/community/board/controller/BoardController.java
  src/main/java/com/lol/community/board/domain/Board.java
  src/main/java/com/lol/community/board/domain/BoardReaction.java
  src/main/java/com/lol/community/board/dto/request/BoardSearchRequest.java
  src/main/java/com/lol/community/board/dto/response/BoardMainResponse.java
  src/main/java/com/lol/community/board/dto/response/BoardMainView.java
  src/main/java/com/lol/community/board/repository/BoardReactionRepository.java
  src/main/java/com/lol/community/board/repository/BoardRepository.java
  src/main/java/com/lol/community/board/service/BoardReactionService.java
  src/main/java/com/lol/community/board/service/BoardService.java
  src/main/java/com/lol/community/board/service/BoardServiceImpl.java
  src/main/java/com/lol/community/category/domain/Category.java
  src/main/java/com/lol/community/category/dto/response/CategoryResponse.java
  src/main/java/com/lol/community/category/service/CategoryService.java
  src/main/java/com/lol/community/comment/Comment.java
  src/main/java/com/lol/community/comment/repository/CommentRepository.java
  src/main/java/com/lol/community/comment/service/CommentService.java
  src/main/java/com/lol/community/user/domain/Grade.java
  src/main/resources/static/css/main.css
  src/main/resources/static/css/normalize.css
  src/main/resources/static/js/article.js
  src/main/resources/templates/board.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/head.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/report.html
Labels: BE🍴, 개발💻🖱️, QA🔨, feat🚀, FE🎨

#35 feat[#34] 게시판 파트 로그인 연동
  src/main/java/com/lol/community/board/controller/BoardApiController.java
  src/main/java/com/lol/community/board/controller/BoardController.java
  src/main/java/com/lol/community/board/dto/request/BoardRequest.java
  src/main/java/com/lol/community/board/dto/response/BoardResponse.java
  src/main/java/com/lol/community/board/service/BoardService.java
  src/main/java/com/lol/community/board/service/BoardServiceImpl.java
  src/main/java/com/lol/community/user/controller/LoginController.java
  src/main/java/com/lol/community/user/controller/UserController.java
  src/main/java/com/lol/community/user/domain/User.java
  src/main/java/com/lol/community/user/repository/UserRepository.java
  src/main/java/com/lol/community/user/repository/UserRepositoryImpl.java
  src/main/java/com/lol/community/user/service/LoginService.java
  src/main/java/com/lol/community/user/service/UserService.java
  src/main/resources/static/css/addUserForm.css
  src/main/resources/static/css/editUserForm.css
  src/main/resources/static/css/newArticle.css
  src/main/resources/static/index.html
  src/main/resources/static/js/article.js
  src/main/resources/templates/board.html
  src/main/resources/templates/board/articles.html
  src/main/resources/templates/board/newArticle.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/newArticle.html
  src/test/java/com/lol/community/user/service/UserServiceImplTest.java
Labels: bug, BE🍴, QA🔨, feat🚀, FE🎨

#40 fix[#36] 자유 게시판 권한 관리 기능 수정
  README.md
  build.gradle
  src/main/java/com/lol/community/board/controller/BoardController.java
  src/main/java/com/lol/community/board/domain/Board.java
  src/main/java/com/lol/community/board/dto/BoardSearch.java
  src/main/java/com/lol/community/board/dto/request/BoardSearchRequest.java
  src/main/java/com/lol/community/board/dto/response/BoardResponse.java
  src/main/java/com/lol/community/board/repository/BoardRepository.java
  src/main/java/com/lol/community/board/service/BoardService.java
  src/main/java/com/lol/community/board/service/BoardServiceImpl.java
  src/main/java/com/lol/community/global/exception/ExceptionType.java
  src/main/java/com/lol/community/user/domain/Grade.java
  src/main/java/com/lol/community/user/service/UserService.java
  src/main/resources/templates/board/articles.html
  src/main/resources/templates/layout/header.html
Labels: bug, BE🍴, QA🔨, feat🚀

#43 feat : 메인 화면 디자인 수정
  src/main/resources/static/css/addUserForm.css
  src/main/resources/static/css/article.css
  src/main/resources/static/css/editUserForm.css
  src/main/resources/static/css/loginForm.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/newArticle.css
  src/main/resources/static/css/userAuth.css
  src/main/resources/static/img/arrow.png
  src/main/resources/static/img/authBtn.png
  src/main/resources/static/img/banner.png
  src/main/resources/static/img/btn_write.png
  src/main/resources/static/img/footer_img.png
  src/main/resources/static/img/footer_img_dohan.png
  src/main/resources/static/img/pencil.png
  src/main/resources/static/img/plus.png
  src/main/resources/static/img/search.png
  src/main/resources/templates/board/articles.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/login/loginForm.html
  src/main/resources/templates/users/addUserForm.html
  src/main/resources/templates/users/editUserForm.html
  src/main/resources/templates/users/userAuth.html
Labels: FE🎨

#42 feat[#7] 댓글 CRUD 구현
  build.gradle
  src/main/java/com/lol/community/board/controller/BoardController.java
  src/main/java/com/lol/community/board/domain/Board.java
  src/main/java/com/lol/community/board/domain/BoardReaction.java
  src/main/java/com/lol/community/board/dto/request/BoardReactionDTO.java
  src/main/java/com/lol/community/board/dto/request/BoardSearchRequest.java
  src/main/java/com/lol/community/board/repository/BoardReactionRepository.java
  src/main/java/com/lol/community/board/repository/BoardRepository.java
  src/main/java/com/lol/community/board/service/BoardReactionService.java
  src/main/java/com/lol/community/comment/Comment.java
  src/main/java/com/lol/community/comment/controller/CommentController.java
  src/main/java/com/lol/community/comment/domain/Comment.java
  src/main/java/com/lol/community/comment/dto/CommentPageRequestDTO.java
  src/main/java/com/lol/community/comment/dto/CommentPageResponseDTO.java
  src/main/java/com/lol/community/comment/dto/CommentRequestDTO.java
  src/main/java/com/lol/community/comment/dto/CommentResponseDTO.java
  src/main/java/com/lol/community/comment/repository/CommentRepository.java
  src/main/java/com/lol/community/comment/repository/CustomCommentRepository.java
  src/main/java/com/lol/community/comment/repository/CustomCommentRepositoryImpl.java
  src/main/java/com/lol/community/comment/service/CommentService.java
  src/main/java/com/lol/community/comment/service/CommentServiceImpl.java
  src/main/java/com/lol/community/global/config/QuerydslConfig.java
  src/main/java/com/lol/community/global/config/WebSecurityConfig.java
  src/main/java/com/lol/community/reaction/controller/LikeReactionController.java
  src/main/java/com/lol/community/reaction/domain/LikeReactionComment.java
  src/main/java/com/lol/community/reaction/dto/LikeReactionCommentDTO.java
  src/main/java/com/lol/community/reaction/repository/LikeReactionCommentRepository.java
  src/main/java/com/lol/community/reaction/service/LikeReactionService.java
  src/main/java/com/lol/community/reaction/service/LikeReactionServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/icon/thumb-up-fill.png
  src/main/resources/static/icon/thumb-up.png
  src/main/resources/templates/board/article.html
  src/main/resources/templates/comment/list.html
  src/test/java/com/lol/community/comment/controller/CommentControllerTest.java
Labels: BE🍴, 개발💻🖱️, QA🔨, feat🚀
